### PR TITLE
reduced the volume of metrics

### PR DESCRIPTION
**Pull request by tumani1**
reduced the volume of metrics

### CODE REVIEW

**Review by xaionaro — APPROVED** [review]

**Comment by xaionaro** [comment]
Added method `SetDefaultPercentiles` and fixed unit-tests in: https://github.com/xaionaro-go/metrics/blob/master/registry.go#L566.

**Comment by tumani1** [comment]
thx, need to close this merge request and check your fix in production

**Comment by xaionaro** [comment]
@tumani1 : Please let me know if you will find any problems. I'll try to handle that.
I haven't tested this in production at all. Only on unit-tests, yet :(

**Comment by tumani1** [comment]
@xaionaro sure, I'll let you know if we have any problems

**Pull request closed without merging**
